# What is everyone's email addresses (and print them too)?

PREFIX afn: <http://jena.apache.org/ARQ/function#>
PREFIX ab: <http://learningsparql.com/ns/addressbook#>
SELECT ?firstname ?email
WHERE
{
    ?person ab:firstname ?firstname .
    ?person ab:email     ?email     .
    FILTER(CONTAINS(?firstname, "i"))
    FILTER(afn:print(?email))
}
