# Construct new triples for everyone's name and email addresses as JSON

PREFIX afn: <http://jena.apache.org/ARQ/function#>
PREFIX ab: <http://learningsparql.com/ns/addressbook#>
JSON {
    "firstname": ?firstname, 
    "email": ?email
}
WHERE {
    {
        SELECT ?firstname
        WHERE { 
            ?person ab:firstname ?firstname
        }
    }
    {
        SELECT ?email
        WHERE { 
            ?person ab:email ?email
        }
    }
}

