# List everyone who does not have a mobile number.

PREFIX ab: <http://learningsparql.com/ns/addressbook#> 
SELECT ?firstname ?lastname
WHERE
{
    ?person ab:lastname  ?lastname      ;
            ab:firstname ?firstname     .
    FILTER NOT EXISTS {
        ?person ab:mobileTel ?mobile   . 
    }
}
