# List everyone who has a yahoo email address.

PREFIX ab: <http://learningsparql.com/ns/addressbook#> 
SELECT ?firstname ?lastname ?email
WHERE
{
    ?person ab:email     ?email             ;
            ab:firstname ?firstname         ;
            ab:lastname  ?lastname          .
    FILTER (regex(?email, "yahoo", "i"))    .
}
