# List everyone who either has a nickname or a mobile number.

PREFIX ab: <http://learningsparql.com/ns/addressbook#> 
SELECT ?firstname ?lastname ?nickname ?mobile
WHERE
{
    ?person ab:lastname  ?lastname      ;
            ab:firstname ?firstname     .
    OPTIONAL{ ?person ab:nickname ?nickname . }
    OPTIONAL{ ?person ab:mobileTel ?mobile . }
    FILTER( bound(?nickname) || bound(?mobile))

}
