# Select all triples in blazegraph.

PREFIX ab: <http://learningsparql.com/ns/addressbook#>
SELECT ?s ?p ?o
WHERE
{
    SERVICE <http://127.0.0.1:9999/blazegraph/sparql>
    {
        SELECT ?s ?p ?o
        WHERE {}
    }
}
